<?php declare(strict_types = 1);
/**
 * 
 * Verisanat v.4
 * 
 * Object oriented, strongly typed, up to date software in modular structure for 
 * creating web applications. Designed and documented for developers.
 * 
 * Release VTS.443.222 - Open Source Package - MPL 2.0 Licensed.
 * 
 * https://onurgunescomtr@bitbucket.org/onurgunescomtr/verisanat-v.4.git
 * https://github.com/onurgunescomtr/verisanat
 * 
 * @package		Verisanat v.4.4.3 "Rembrandt"
 * @subpackage  VTS.443.222 [Tr]Verisanat Tam Sürüm - [En]Verisanat Full Version 
 * 
 * @author		Onur Güneş  https://www.facebook.com/onur.gunes.developer
 *                          https://www.twitter.com/onurgunescomtr
 *                          verisanat@outlook.com
 *                          https://www.verisanat.com/contact
 * 
 * @copyright	Copyright (c) 2012 - 2021 Onur Güneş
 *              https://www.verisanat.com
 *              https://www.onurgunes.com.tr
 *              [En]All Rights Reserved. [Tr]Tüm hakları saklıdır.
 * 
 * @license		Mozilla Public License 2.0
 *              https://choosealicense.com/licenses/mpl-2.0
 * 
 *              This Source Code Form is subject to the terms of the Mozilla Public
 *              License, v. 2.0. If a copy of the MPL was not distributed with this
 *              file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * 
 * @link		https://www.verisanat.com
*/

$translate = array(
    'register' => 'Register',
    'home' => 'Home',
    'order' => 'Order',
    'greet' => 'Greetings, ',
    'mypage' => 'My Page',
    'account' => 'Account',
    'accountId' => 'Account Id',
    'google_map' => 'Google Maps',
    'create_new_account' => 'Create New Account',
	'creating_new_account' => 'Account Creation',
	'account_created' => 'Your Account is Created',
	'already_account' => 'I already have an account',
	'use_verification_link' => 'Please click below the link to verify your email address.',
	'happy_days' => 'We wish you a pleasant day!',
    'reset_password' => 'Reset Password',
    'renew_my_password' => 'Send e-mail',
    'products_services' => 'Products/Services',
    'my_active_services' => 'My Active Services',
    'billing' => 'Billing',
    'my_transactions' => 'My Transactions',
    'my_invoices' => 'My Invoices',
    'support' => 'Support',
    'create_new_support_ticket' => 'Create New Support Ticket',
    'your_message' => 'Your Message',
    'faq' => 'Frequently Asked Questions',
    'login_to_your_account' => 'Login to your Account',
    'login_screen' => 'Login Screen',
    'user_processes' => 'User Processes',
    'my_account' => 'My Account',
    'prop_detail' => 'Properties and Details',
    'add_to_account' => 'Hesabıma Ekle',
    'request_info' => 'Get More Information',
    'edit_profile' => 'Edit Profile',
    'logout' => 'Logout',
    'help_pages' => 'Help Pages',
    'search' => 'Search',
    'signout' => 'Sign Out',
    'addr_telf' => 'Office Address and Communication Info',
    'writetous' => 'Write to Us',
    'signin' => 'Sign In',
    'id' => 'ID',
    'manage' => 'Manage',
    'view_details' => 'View Details',
    'registered_email_address' => 'Registered Email Address',
    'account_credit' => 'Account Credit',
    'view_statement' => 'View Statement',
    'last' => 'Last',
    'English' => 'English',
    'Turkish' => 'Turkish',
    'comission_percentage' => 'Comission Percentage',
    'invoice' => 'Invoice',
    'invoices' => 'Invoices',
    'pay_now' => 'Pay Now',
    'created' => 'Created',
    'due_date' => 'Due Date',
    'amount' => 'Amount',
    'status' => 'Status.',
    'about_us' => 'About Us',
    'about' => 'About',
    'date' => 'Date.',
    'account_name' => 'Account Name',
    'company_name' => 'Company Name',
    'write_your_email' => 'Please enter your e-mail address',
    'email_address' => 'Email Address',
	'email_address_placeholder' => 'i.e. jane.ashwood@email.com',
    'please_dont_share' => 'Please do not share your password with anyone',
    'telephone_no' => 'Mobile No',
    'property_wish' => 'Property you interested in',
    'address_line_1' => 'Address Line 1',
    'address_line_2' => 'Address Line 2',
    'state' => 'State',
    'region' => 'Region',
    'postcode' => 'Postcode',
    'country' => 'Country',
    'phone_number' => 'Phone Number',
    'save_changes' => 'Save Changes',
    'cancel' => 'Cancel',
    'login' => 'Login',
    'username' => 'Username',
    'password' => 'Password',
	'password_placeholder' => 'your password',
	'password_explain' => 'Your password must contain a letter, a number, one or more of <br> these (- . @ ! +) and a total 8 characters minimum.',
	'password_confirm' => 'your password again',
    'registration' => 'Registration',
    'full_name' => 'Full Name',
    'confirm' => 'Confirm',
    'email' => 'Email',
    'enter_above_code' => 'Enter Above Code',
    'contact_us' => 'Get in Touch',
    'name_placeholder' => 'i.e. Jane Ashwood',
    'namesurname' => 'Name and Surname',
    'message' => 'Message',
    'notice_board' => 'Notice Board',
    'all_support_tickets' => 'All Support Tickets',
    'view' => 'View',
    'new_ticket' => 'New Ticket',
    'error_invalid_user_pass' => 'Invalid User ID or Password',
    'no_tickets' => 'You do not have any support ticket',
    'payment_method' => 'Payment Method',
    'continue' => 'Continue',
    'sentTo' => 'Sent To',
    'sendDate' => 'Send Date',
    'orders' => 'Orders',
    'close' => 'Close',
    'exportCSV' => 'Export CSV',
    'exportPDF' => 'Export PDF',
    'customer' => 'Customer',
    'vendor' => 'Vendor',
    'cash' => 'Cash',
    'bank' => 'Bank',
    'investor' => 'Investor',
    'partner' => 'Partner',
    'employee' => 'Employee',
    'consultant' => 'Consultant',
    'income' => 'Income',
    'expense' => 'Expense',
    'tax' => 'Tax',
    'creditCard' => 'Credit Card',
    'inventory' => 'Inventory',
    'other' => 'Other',
    'chooseContact' => 'Choose Contact',
    'addNewGroup' => 'Add New Group',
    'groupName' => 'Group Name',
    'submit' => 'Submit',
    'transfer' => 'Transfer',
    'allInvoices' => 'All Invoices',
    'paid' => 'Paid',
    'overDue' => 'Unpaid',
    'cancelled' => 'Cancelled',
    'refunded' => 'Refunded',
    'invoiceDate' => 'Invoice Date',
    'clientName' => 'Client Name',
    'chooseCustomer' => 'Choose Customer',
    'addItem' => 'Add Item',
    'addNote' => 'Add Note',
    'manageProducts' => 'Manage Products',
    'pending' => 'Pending',
    'inProgress' => 'In Progress',
    'active' => 'Active',
    'fraud' => 'Fraud',
    'dashBoard' => 'Dashboard',
    'quickAccess' => 'Quick Access',
    'accounts' => 'Accounts',
    'tickets' => 'Tickets',
    'contact' => 'Contact Us',
    'balance' => 'Balance',
    'customerAccount' => 'Customer Account',
    'liabilities' => 'Liabilities',
    'account_description' => 'Account Description',
    'type' => 'Type',
    'sendEmailNotification' => 'Send Email Notification',
    'phone' => 'Phone',
    'chooseGroup' => 'Choose Group',
    'city' => 'City',
    'addClient' => 'Add Client',
    'frequency' => 'Frequency',
    'monthly' => 'Monthly',
    'yearly' => 'Yearly',
    'note' => 'notes',
    'listOfProductServices' => 'List Of Product And Service',
    'invoiceId' => 'Invoice Id',
    'clientId' => 'Client Id',
    'nextDueDate' => 'Next Due Date',
    'total' => 'Total',
    'add_new_order' => 'Add New Order',
    'chooseProduct' => 'Choose Product',
    'yes' => 'Yes',
    'no' => 'No',
    'print' => 'Print This Page',
    'value' => 'Value',
    'paymentFrom' => 'Payment From',
    'paymentTo' => 'Payment To',
    'aresureDelAccount' => 'Are You Sure, You want to delete this Account?',
    'delete_account' => 'Delete Account',
    'delete' => 'Delete',
    'choosecountry' => 'Choose a country...',
    'view_all_accounts' => 'View All Accounts',
    'back_to_list' => 'Back To The List',
    'edit_role' => 'Edit Role',
    'check_uncheck' => 'Check All / Uncheck All',
    'view_support_ticket' => 'View Support Tickets',
    'send' => 'Send',
    'save_contents' => 'Save Contents',
    'view_invoice_link' => 'View Invoice Link',
    'item' => 'Item',
    'choose_an_account' => 'Choose an Account',
    'choose_contact' => 'Choose a Contact',
    'accept' => 'Accept',
    'to' => 'To',
    'reply' => 'Reply',
    'qty' => 'Quantity',
    'lets_start' => 'Lets Start',
    'changelog' => 'ChangeLog',
    'howto' => 'How to Use',
    'doc_moduls' => 'Moduls',
    'doc_internals' => 'Internal Structure',
    'documentation' => 'Docs',
    'app' => 'Application',
    'struct' => 'Structure',
    'properties' => 'Properties',
	'term_conditions' => 'Terms and Conditions',
	'privacy_policy' => 'Privacy Policy',
    'contact_acceptance' => 'Using our contact form is under policies and terms.<br>',
	'register_acceptance' => 'Upon registration, you agree on policies and terms.<br>',
	'login_acceptance' => 'You can take a look terms and policies you accepted. <br>',
    'warning_report' => 'Completed',
    'error_report' => 'Failed',
    'module_request_unit_fail' => 'A non-existent unit requested from module : ',
    'http_404_module_unit' => 'Requested module unit unavailable.',
    'http_404_202' => '404.002.There is no such thing.',
    'http_404_004' => '404.004.Module data area is undefined.',
    'app_contact_name' => 'Contact',
    'app_contact_title' => 'Get in touch',
    'app_about_name' => 'About',
    'app_about_title' => 'About this App',
    'language_button_non' => 'App languge support is disabled',
    'enter_new_password' => 'Enter your new password',
    'email_request_change' => '<small class="form-text text-muted">To continue password change, required information will be sent to <br> the email address registered with your account.</small>'
);
$text_translate = array(
    'tanim' => 'descriptions paragraphs'
);
$uri_translate = [
	'register' => 'create-a-new-account',
	'login' => 'login-to-your-account',
	'terms-and-conditions' => 'terms-and-conditions',
	'privacy-policy' => 'privacy-policy',
    'request-password-recovery' => 'renew-my-password',
    'new-password' => 'my-new-password',
    'password-change-email-verify-link' => 'yeni-sifrenizi-olusturun'
];
?>