<?php declare(strict_types = 1);
/**
 * 
 * Verisanat v.4
 * 
 * Object oriented, strongly typed, up to date software in modular structure for 
 * creating web applications. Designed and documented for developers.
 * 
 * Release VTS.443.222 - Open Source Package - MPL 2.0 Licensed.
 * 
 * https://onurgunescomtr@bitbucket.org/onurgunescomtr/verisanat-v.4.git
 * https://github.com/onurgunescomtr/verisanat
 * 
 * @package		Verisanat v.4.4.3 "Rembrandt"
 * @subpackage  VTS.443.222 [Tr]Verisanat Tam Sürüm - [En]Verisanat Full Version 
 * 
 * @author		Onur Güneş  https://www.facebook.com/onur.gunes.developer
 *                          https://www.twitter.com/onurgunescomtr
 *                          verisanat@outlook.com
 *                          https://www.verisanat.com/contact
 * 
 * @copyright	Copyright (c) 2012 - 2021 Onur Güneş
 *              https://www.verisanat.com
 *              https://www.onurgunes.com.tr
 *              [En]All Rights Reserved. [Tr]Tüm hakları saklıdır.
 * 
 * @license		Mozilla Public License 2.0
 *              https://choosealicense.com/licenses/mpl-2.0
 * 
 *              This Source Code Form is subject to the terms of the Mozilla Public
 *              License, v. 2.0. If a copy of the MPL was not distributed with this
 *              file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * 
 * @link		https://www.verisanat.com
*/

$ceviri = array(
    'register' => 'Kayıt Ol',
    'home' => 'Ana Sayfa',
    'order' => 'Sipariş',
    'greet' => 'Hoşgeldiniz, ',
    'mypage' => 'Benim Sayfam',
    'account' => 'Hesap',
    'accountId' => 'Hesap No',
    'google_map' => 'Google Haritalar',
    'create_new_account' => 'Hesabınızı Oluşturun',
	'creating_new_account' => 'Hesap Açılışı',
	'account_created' => 'Hesabınız Açılmıştır',
	'already_account' => 'Hesabım Var',
	'use_verification_link' => 'Lütfen aşağıdaki bağlantıyı kullanarak e-posta adresinizi doğrulayın.',
	'happy_days' => 'Mutlu günler dileklerimizle!',
    'reset_password' => 'Şifremi Unuttum',
    'renew_my_password' => 'Şifremi Yenile',
    'products_services' => 'Ürünler ve Servisler',
    'my_active_services' => 'Siparişlerim',
    'billing' => 'Faturalama',
    'my_transactions' => 'Hesap Hareketlerim',
    'my_invoices' => 'Faturalarım',
    'support' => 'Destek',
    'create_new_support_ticket' => 'Yeni Destek Talebi Oluştur',
    'your_message' => 'İletiniz',
    'faq' => 'Sıkça Sorulan Sorular',
    'login_to_your_account' => 'Hesabınıza Giriş Yapın',
    'login_screen' => 'Giriş Ekranı',
    'user_processes' => 'Kullanıcı İşlemleri',
    'my_account' => 'Hesabım',
    'prop_detail' => 'Özellikler ve Detaylar',
    'add_to_account' => 'Add to my Account',
    'request_info' => 'Bilgi Talebi',
    'edit_profile' => 'Profili Düzenle',
    'logout' => 'Çıkış Yap',
    'help_pages' => 'Yardım Sayfaları',
    'search' => 'Ara',
    'signout' => 'Oturumu Kapat',
    'addr_telf' => 'Adres ve İletişim Bilgilerimiz',
    'writetous' => 'Bizimle İletişime Geçin',
    'signin' => 'Oturum Açın',
    'id' => 'No',
    'manage' => 'İşlemler',
    'view_details' => 'Detayları Görüntüle',
    'registered_email_address' => 'Kayıtlı eMail adresi',
    'account_credit' => 'Hesap Kredisi',
    'view_statement' => 'Bildiriyi Görüntüle',
    'last' => 'Son',
    'English' => 'İngilizce',
    'Turkish' => 'Türkçe',
    'comission_percentage' => 'Komisyon Oranı',
    'invoice' => 'Fatura',
    'invoices' => 'Faturalar',
    'pay_now' => 'Ödeme Yap',
    'created' => 'Oluşturuldu',
    'due_date' => 'Son Ödeme Tarihi',
    'amount' => 'Tutar',
    'status' => 'Durum',
    'about_us' => 'Hakkımızda',
    'about' => 'Hakkında',
    'date' => 'Tarih',
    'account_name' => 'Hesap Adı',
    'company_name' => 'Şirket Adı',
    'write_your_email' => 'Lütfen e-posta Adresinizi Yazın',
    'email_address' => 'E-posta Adresiniz',
	'email_address_placeholder' => 'ör. karaca.ipek@posta.com',
    'please_dont_share' => 'Lütfen şifrenizi kimse ile paylaşmayınız.',
    'telephone_no' => 'Telefon Numaranız',
    'property_wish' => 'İlgilendiğiniz İlan',
    'address_line_1' => 'Adres Satırı 1',
    'address_line_2' => 'Adres Satırı 2',
    'state' => 'İlçe',
    'region' => 'Bölge',
    'postcode' => 'Posta Kodu',
    'country' => 'Ülke',
    'phone_number' => 'Telefon Numarası',
    'save_changes' => 'Değişiklikleri Kaydet',
    'cancel' => 'İptal',
    'login' => 'Giriş Yap',
    'username' => 'Kullanıcı Adı',
    'password' => 'Şifre',
	'password_placeholder' => 'şifreniz',
	'password_explain' => 'Şifreniz en az bir sayı, şu işaretlerden birini yada benzerini (- . @ ! +) <br>ve bir büyük harf içermeli ve sekiz yada daha fazla karakterden oluşmalıdır',
	'password_confirm' => 'şifreniz tekrar',
    'registration' => 'Kayıt',
    'full_name' => 'Tam Adı',
    'confirm' => 'Onayla',
    'email' => 'Email',
    'enter_above_code' => 'Yukarıdaki Kodu Girin',
    'contact_us' => 'İletişime Geçin',
    'name_placeholder' => 'ör. Ali Kasapoğlu',
    'namesurname' => 'Adınız ve Soyadınız',
    'message' => 'İleti',
    'notice_board' => 'Kampanyalar',
    'all_support_tickets' => 'Tüm Destek Talepleri',
    'view' => 'Görüntüle',
    'new_ticket' => 'Yeni Talep',
    'error_invalid_user_pass' => 'Geçersiz kullanıcı adı yada şifre',
    'no_tickets' => 'Destek talebiniz bulunmuyor',
    'payment_method' => 'Ödeme Yöntemi',
    'continue' => 'Devam',
    'sentTo' => 'Gönderilecek Adres',
    'sendDate' => 'Gönderim Tarihi',
    'orders' => 'Siparişler',
    'close' => 'Kapat',
    'exportCSV' => 'Excele Al CSV',
    'exportPDF' => 'PDF Olarak Al',
    'customer' => 'Müşteri',
    'vendor' => 'Tedarikçi',
    'cash' => 'Nakit',
    'bank' => 'Banka',
    'investor' => 'Yatırımcı',
    'partner' => 'Ortak',
    'employee' => 'Çalışan',
    'consultant' => 'Danışman',
    'income' => 'Gelir',
    'expense' => 'Gider',
    'tax' => 'Vergi',
    'creditCard' => 'Kredi Kartı',
    'inventory' => 'Şubeler ve Depolar',
    'other' => 'Diğer',
    'chooseContact' => 'Kişi Seç',
    'addNewGroup' => 'Yeni Grup Oluştur',
    'groupName' => 'Grup Adı',
    'submit' => 'Tamamla',
    'transfer' => 'Transfer',
    'allInvoices' => 'Tüm Faturalar',
    'paid' => 'Ödenmiş',
    'overDue' => 'Zamanı Geçmiş',
    'cancelled' => 'İptal Edilmiş',
    'refunded' => 'Geri İade',
    'invoiceDate' => 'Faturalama Tarihi',
    'clientName' => 'Müşteri Adı',
    'chooseCustomer' => 'Müşteri Seç',
    'addItem' => 'Ekle',
    'addNote' => 'Not Ekleyin',
    'manageProducts' => 'Ürünleri Yönet',
    'pending' => 'Bekleyen',
    'inProgress' => 'İşleniyor',
    'active' => 'Aktif',
    'fraud' => 'Geçersiz',
    'dashBoard' => 'Yönetim Ekranı',
    'quickAccess' => 'Hızlı Erişim',
    'accounts' => 'Hesaplar',
    'tickets' => 'Talepler',
    'contact' => 'İletişim',
    'balance' => 'Bakiye',
    'customerAccount' => 'Müşteri Hesabı',
    'liabilities' => 'Yükümlülükler',
    'account_description' => 'Hesap Tanımı',
    'type' => 'Tipi',
    'sendEmailNotification' => 'Bilgilendirme emaili gönder',
    'phone' => 'Telefon',
    'chooseGroup' => 'Grup Seç',
    'city' => 'Şehir',
    'addClient' => 'Müşteri Ekle',
    'frequency' => 'Terar Aralığı',
    'monthly' => 'Aylık',
    'yearly' => 'Yıllık',
    'note' => 'Notlar',
    'listOfProductServices' => 'Ürün ve Servis Listesi',
    'invoiceId' => 'Fatura No',
    'clientId' => 'Müşteri No',
    'nextDueDate' => 'Sonraki Ödeme Tarihi',
    'total' => 'Genel Toplam',
    'add_new_order' => 'Yeni Sipariş Ekle',
    'chooseProduct' => 'Ürün Seçimi',
    'yes' => 'Evet',
    'no' => 'Hayır',
    'print' => 'Bu sayfayı yazdır',
    'value' => 'Değer',
    'paymentFrom' => 'Ödemeyi Gönderen',
    'paymentTo' => 'Ödemeyi Alan',
    'aresureDelAccount' => 'Bu hesabı silmek istediğinize emin misiniz? ',
    'delete_account' => 'Hesabı Sil',
    'delete' => 'Sil',
    'choosecountry' => 'Bir ülke seçin...',
    'view_all_accounts' => 'Tüm hesapları görüntüle',
    'back_to_list' => 'Listeye geri dön',
    'edit_role' => 'Yetkileri düzenle',
    'check_uncheck' => 'Hepsini seç / Seçimi Temizle',
    'view_support_ticket' => 'Destek Taleplerini Görüntüle',
    'send' => 'Gönder',
    'save_contents' => 'İçeriği Kaydet',
    'view_invoice_link' => 'Fatura bağlantısını görüntüle',
    'item' => 'Parça',
    'choose_an_account' => 'Hesap Seçin',
    'choose_contact' => 'Kişi Seçin',
    'accept' => 'Kabul Et',
    'to' => 'Alıcı',
    'reply' => 'Cevapla',
    'qty' => 'Adet',
    'lets_start' => 'Kullanmaya Başlayın',
    'changelog' => 'Değişim Kayıtları',
    'howto' => 'Nasıl Kullanılır',
    'doc_moduls' => 'Modüller',
    'doc_internals' => 'İç Yapı',
    'documentation' => 'Dökümantasyon',
    'app' => 'Uygulama',
    'struct' => 'Yapılandırma',
    'properties' => 'Özellikleri',
	'term_conditions' => 'Şartlar ve Koşullar',
	'privacy_policy' => 'Gizlilik Politikası',
    'contact_acceptance' => 'İletişim formunu kullanarak ilgili hükümleri kabul etmektesiniz <br>',
	'register_acceptance' => 'Kayıt olarak ilgili hükümleri kabul etmektesiniz. <br>',
	'login_acceptance' => 'Giriş yaparak ilgili hükümleri kabul etmektesiniz. <br>',
    'warning_report' => 'Tamamlandı',
    'error_report' => 'Başarısız',
    'module_request_unit_fail' => 'Var olmayan nesne talep edildi : ',
    'http_404_module_unit' => 'İstenilen öğe bulunamadı',
    'http_404_202' => '404.002.Yok.',
    'http_404_004' => '404.004.Modül veri alanı tanımsız.',
    'app_contact_name' => 'İletişim',
    'app_contact_title' => 'İletişime Geçin',
    'app_about_name' => 'Hakkında',
    'app_about_title' => 'Hakkında',
    'language_button_non' => 'Uygulama dil desteği kapalı durumdadır.',
    'enter_new_password' => 'Yeni Şifrenizi Oluşturun',
    'email_request_change' => '<small class="form-text text-muted">Hesabınızı oluştururken kullandığınız e-posta adresine <br> yeni şifrenizi oluşturabilmeniz için gerekli bilgiler <br> gönderilecektir. </small>'
);
$text_ceviri = array(
    'tanim' => 'tanımlar paragraflar'
);
$uri_ceviri = [
	'register' => 'hesap-acilisi',
	'login' => 'giris-yap',
	'terms-and-conditions' => 'kullanim-sartlari',
	'privacy-policy' => 'gizlilik-politikasi',
    'request-password-recovery' => 'sifre-yenileme-talebi',
    'new-password' => 'yeni-sifrem',
    'password-change-email-verify-link' => 'yeni-sifrenizi-olusturun'
];
?>